routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');

Auth::routes();
Route::get('/register', 'RegistrationController@userRegistrationForm')->name('userRegistrationForm');
Route::get('/register/delivery-boy', 'RegistrationController@userRegistrationForm')->name('deliveryBoyRegistrationForm');
Route::post('/register', 'RegistrationController@userRegistrationSubmit')->name('userRegistrationSubmit');

// ajax routes
Route::get('/get/district', 'UserController@getDistrict');
Route::get('/get/upazila', 'UserController@getUpazila');
Route::get('/get/tracking_id', 'UserController@product_tracking');


// admin routes
Route::get('/home', 'HomeController@index')->name('home')->middleware('suspend');
Route::get('/personal/profile', 'HomeController@personalProfile')->name('personalProfile')->middleware('suspend');
Route::get('/update/profile', 'HomeController@updateProfile')->name('updateProfile')->middleware('suspend');

Route::group(['prefix' => 'admin', 'middleware' => ['suspend']], function(){
    // Notifications
    Route::get('notifications', 'NotificationController@index')->name('notifications');
    Route::get('notification/{id}/delete', 'NotificationController@notificationDelete')->name('notificationDelete');

    // user update
    Route::get('/user/update/{id}', 'UserController@updateUserForm')->name('updateUserForm');
    Route::post('user/update', 'UserController@updateUser')->name('userRegistration.update');

    // single user view
    Route::get('/user/single/{id}/view', 'UserController@singleUserView')->name('singleUserView');

    Route::group(['middleware' => 'manager'], function(){
        // user registration
        Route::get('/user/registration/{type}', 'UserController@registrationForm')->name('registrationForm');
        Route::post('/user/registration', 'UserController@store')->name('userRegistration.store');

        // user view
        Route::get('/user/all/{type}/view', 'UserController@userList')->name('adminUser.list');

        // delivery boy payment
        Route::get('/payment/admin/history', 'IncomeController@adminPaymentHistory')->name('adminPaymentHistory');
        Route::post('/payment/admin/make', 'IncomeController@makePayment')->name('makePayment');
        Route::get('/payment/admin/{type}/{id}', 'IncomeController@changeOrDeletePaymentHistory')->name('changeOrDeletePaymentHistory');

        // merchant fee and payment
        Route::get('payment/merchant/history', 'MerchantTransactionController@merchantPaymentHistory')->name('merchantPaymentHistory');
        Route::get('payment/fee/history', 'MerchantTransactionController@merchantFeeHistory')->name('merchantFeeHistory');
        Route::get('payment/change/status/{type}/{id}', 'MerchantTransactionController@changeMerchantPaymentStatus')->name('changeMerchantPaymentStatus');
        Route::get('fee/change/status/{type}/{id}', 'MerchantTransactionController@changeMerchantFeeStatus')->name('changeMerchantFeeStatus');
        Route::post('payment/make/', 'MerchantTransactionController@makeMerchantPayment')->name('makeMerchantPayment');
        //fee
        Route::post('fee/make/', 'MerchantTransactionController@getDeliveryFeeFromMerchant')->name('getDeliveryFeeFromMerchant');

        // user suspend, delete and approve confirmation
        Route::get('/user/suspend/{id}/confirmation', 'UserController@userSuspendConfirmation')->name('userSuspendConfirmation');
        Route::get('/user/delete/{id}/confirmation', 'UserController@userDeleteConfirmation')->name('userDeleteConfirmation');
        Route::get('/user/approve/{id}/confirmation', 'UserController@userApproveConfirmation')->name('userApproveConfirmation');

        // admin order modify routes
        Route::get('/order/{type}/list', 'AdminOrderController@orderList')->name('orderListForAdmin');
        Route::post('/order/update/accept', 'AdminOrderController@acceptOrder')->name('acceptOrder');

        // admin delivery
        Route::get('/delivery/{type}/list', 'AdminDeliveryController@deliveryListForAdmin')->name('deliveryListForAdmin');
        Route::get('/products/change/{id}/{status_id}/status', 'AdminDeliveryController@changeStatus')->name('changeStatus');
        Route::post('assign/delivery/boy', 'AdminDeliveryController@assignForDeliver')->name('assignForDeliver');

        // resource routes
        Route::resource('area', 'AreaController');
        Route::resource('branch', 'BranchController');
        Route::resource('delivery_system', 'DeliverySystemController');
        Route::resource('cancel_reason', 'CancelController');
    });

    // merchant routes
    Route::group(['middleware'=> 'merchant', 'prefix' => 'merchant'], function (){
        Route::resource('order_request', 'OrderRequestController');
        Route::get('order/list/{type}', 'MerchantOrderController@merchantOrderList')->name('merchantOrderList');
        Route::get('order/change/status/{id}/{status}', 'MerchantOrderController@changeStatusByMerchant')->name('changeStatusByMerchant');

        // merchant payment list
        Route::get('payment/list', 'MerchantTransactionController@merchantPaymentList')->name('merchantPaymentList');
        Route::get('delivery/fee/payment/list', 'MerchantTransactionController@merchantDeliveryFeePaymentHistory')->name('merchantDeliveryFeePaymentHistory');
        Route::get('/accept/change/{type}/{id}', 'MerchantTransactionController@acceptOrRejectMerchantPayment')->name('acceptOrRejectMerchantPayment');
        Route::get('fee/change/{type}/{id}', 'MerchantTransactionController@acceptOrRejectMerchantDeliveryFee')->name('acceptOrRejectMerchantDeliveryFee');
    });

    // delivery boy routes
    Route::group(['prefix' => "boy"], function (){
       Route::get('order/{type}/list', 'BoyOrderController@orderList')->name('boy.orderList');
       Route::get('order/pick/{type}/{order_id}', 'BoyOrderController@acceptPickOrder')->name('boy.acceptPickOrder');
       Route::get('order/add/product/{order_id}', 'BoyOrderController@addProductsToOrder')->name('boy.addProductsToOrder');
       Route::post('order/add/product', 'BoyOrderController@addProductsToOrderSubmit')->name('boy.addProductsToOrderSubmit');
       Route::get('order/details/products/{id}', 'BoyOrderController@orderDetails')->name('boy.orderDetails');
       Route::get('order/delivered/office/{id}', 'BoyOrderController@deliveredToOffice')->name('boy.deliveredToOffice'); // notifyable

        // delivery routes for boy
        Route::get('delivery/products/{type}', 'BoyDeliveryController@boyDeliveryList')->name('boyDeliveryList');
        Route::get('delivery/request/accept/{id}', 'BoyDeliveryController@acceptDeliveryRequest')->name('acceptDeliveryRequest');
        Route::get('delivery/request/reject/{id}', 'BoyDeliveryController@rejectDeliveryRequest')->name('rejectDeliveryRequest');
        Route::get('delivery/collect/product/{id}', 'BoyDeliveryController@collectProductForDelivery')->name('collectProductForDelivery');
        Route::get('delivery/complete/confirm/{id}', 'BoyDeliveryController@requestToCompleteDelivery')->name('requestToCompleteDelivery');
        Route::post('delivery/cancel/', 'BoyDeliveryController@cancelOrderByBoy')->name('cancelOrderByBoy');

        // income and payment routes
        Route::get('/income/boy/history', 'IncomeController@boyIncomeHistory')->name('boyIncomeHistory');
        Route::get('/payment/boy/history', 'IncomeController@boyPaymentHistory')->name('boyPaymentHistory');
        Route::get('/payment/accept/boy/{type}/{id}', 'IncomeController@acceptPaymentRequest')->name('acceptPaymentRequest');
    });
});

// default pages (suspend and pending page)
Route::get('/account/suspend/', 'UserController@suspend')->name('userSuspend');
Route::get('/account/pending/', 'UserController@pending')->name('userPending');

app/DeliverySystem.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DeliverySystem extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/DeliverySystemController.php
<?php

namespace App\Http\Controllers;

use App\DeliverySystem;
use Illuminate\Http\Request;

class DeliverySystemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['systems'] = DeliverySystem::all();
        return view('admin.delivery_system.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
           'system_details' => 'required',
           'receiver_boy_fee' => 'required',
           'delivery_boy_fee' => 'required',
           'company_fee' => 'required'
        ]);
        DeliverySystem::create([
            'system_details' => $request->system_details,
            'receiver_boy_fee' => $request->receiver_boy_fee,
            'delivery_boy_fee' => $request->delivery_boy_fee,
            'company_fee' => $request->company_fee
        ]);
        return back()->with('success', "New delivery system created Successfully");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'system_details' => 'required',
            'receiver_boy_fee' => 'required',
            'delivery_boy_fee' => 'required',
            'company_fee' => 'required'
        ]);
        DeliverySystem::find($id)->update([
            'system_details' => $request->system_details,
            'receiver_boy_fee' => $request->receiver_boy_fee,
            'delivery_boy_fee' => $request->delivery_boy_fee,
            'company_fee' => $request->company_fee
        ]);
        return back()->with('success', "Delivery system Updated Successfully");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/delivery_system/index.blade.php
@extends('layouts.adminlayout')

@section("css")
    <link href="{{ asset('admin') }}/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">
@endsection


@section("main_content")
    <div class="row clearfix">
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Delivery System List and Price
                    </h2>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        @if(count($systems) > 0)
                            <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                <thead>
                                <tr>
                                    <th>Delivery System</th>
                                    <th>Picker Boy Fee</th>
                                    <th>Delivery Boy Fee</th>
                                    <th>Company Profit</th>
                                    <th>Total</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($systems as $system)
                                    <tr>
                                        <td>{{ $system->system_details }}</td>
                                        <td>{{ $system->receiver_boy_fee }}</td>
                                        <td>{{ $system->delivery_boy_fee }}</td>
                                        <td>{{ $system->company_fee }}</td>
                                        <td>{{ $system->company_fee + $system->delivery_boy_fee + $system->receiver_boy_fee }}</td>
                                        <td style="width: 10%; white-space: nowrap">
                                            <button type="button" class="btn bg-black" data-toggle="modal" data-target="#smallModal{{ $system->id }}">Update</button>

                                            <div class="modal fade" style="white-space: normal;" id="smallModal{{ $system->id }}" tabindex="-1" role="dialog">
                                                <div class="modal-dialog modal-dialog-center" role="document">
                                                    <div class="modal-content modal-col-green">
                                                        <div class="modal-header">
                                                            <h4 class="modal-title" id="smallModalLabel">Update Delivery System Info</h4>
                                                        </div>
                                                        <form action="{{ route('delivery_system.update', $system->id) }}" method="post">
                                                            @csrf
                                                            @method("put")
                                                            <div class="modal-body">
                                                                <div class="mb-20">
                                                                    <label for="">Delivery Details</label>
                                                                    <input type="text" style="width: 100%" value="{{ $system->system_details }}" class="form-control" name="system_details" placeholder="ex: In Dhaka One Day - 60 TK">
                                                                </div>
                                                                <div class="mb-20">
                                                                    <label for="">Picker Boy Fee</label>
                                                                    <input type="text" style="width: 100%" value="{{ $system->receiver_boy_fee }}" class="form-control" name="receiver_boy_fee" placeholder="Picker or Receiver Boy Fee">
                                                                </div>
                                                                <div class="mb-20">
                                                                    <label for="">Delivery Boy Fee</label>
                                                                    <input type="text" style="width: 100%" value="{{ $system->delivery_boy_fee }}" class="form-control" name="delivery_boy_fee" placeholder="Delivery Boy Fee">
                                                                </div>
                                                                <div class="mb-20">
                                                                    <label for="">Company Profit</label>
                                                                    <input type="text" style="width: 100%" value="{{ $system->company_fee }}" class="form-control" name="company_fee" placeholder="Company Profit">
                                                                </div>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="submit" class="btn btn-link waves-effect" >Update</button>
                                                                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Close</button>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        @else
                            <h2 class="text-center mb-30">No Data Found</h2>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card">
                <div class="header">
                    <h2>Create a New Area</h2>
                </div>
                <div class="body">
                    <form action="{{ route('delivery_system.store') }}" method="post">
                        @csrf
                        <div class="mb-20">
                            <label for="">Delivery Details</label>
                            <input type="text" class="form-control" name="system_details" placeholder="ex: In Dhaka One Day - 60 TK">
                            @if($errors->has('system_details'))
                                <span class="invalid-feedback" role="alert">
                                    <strong style="color: red; font-style: italic">{{ $errors->first('system_details') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="mb-20">
                            <label for="">Picker Boy Fee</label>
                            <input type="text" class="form-control" name="receiver_boy_fee" placeholder="Picker or Receiver Boy Fee">
                            @if($errors->has('receiver_boy_fee'))
                                <span class="invalid-feedback" role="alert">
                                <strong style="color: red; font-style: italic">{{ $errors->first('receiver_boy_fee') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="mb-20">
                            <label for="">Delivery Boy Fee</label>
                            <input type="text" class="form-control" name="delivery_boy_fee" placeholder="Delivery Boy Fee">
                            @if($errors->has('delivery_boy_fee'))
                                <span class="invalid-feedback" role="alert">
                                <strong style="color: red; font-style: italic">{{ $errors->first('delivery_boy_fee') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="mb-20">
                            <label for="">Company Profit</label>
                            <input type="text" class="form-control" name="company_fee" placeholder="Company Profit">
                            @if($errors->has('company_fee'))
                                <span class="invalid-feedback" role="alert">
                                <strong style="color: red; font-style: italic">{{ $errors->first('company_fee') }}</strong>
                            </span>
                            @endif
                        </div>
                        <input type="submit" class="btn btn-success" value="Create Delivery System">
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section("javascript")

    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>

    {{-- --}}
    <script src="{{ asset('admin') }}/js/pages/tables/jquery-datatable.js"></script>


@endsection