routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');

Auth::routes();
Route::get('/register', 'RegistrationController@userRegistrationForm')->name('userRegistrationForm');
Route::get('/register/delivery-boy', 'RegistrationController@userRegistrationForm')->name('deliveryBoyRegistrationForm');
Route::post('/register', 'RegistrationController@userRegistrationSubmit')->name('userRegistrationSubmit');

// ajax routes
Route::get('/get/district', 'UserController@getDistrict');
Route::get('/get/upazila', 'UserController@getUpazila');
Route::get('/get/tracking_id', 'UserController@product_tracking');


// admin routes
Route::get('/home', 'HomeController@index')->name('home')->middleware('suspend');
Route::get('/personal/profile', 'HomeController@personalProfile')->name('personalProfile')->middleware('suspend');
Route::get('/update/profile', 'HomeController@updateProfile')->name('updateProfile')->middleware('suspend');

Route::group(['prefix' => 'admin', 'middleware' => ['suspend']], function(){
    // Notifications
    Route::get('notifications', 'NotificationController@index')->name('notifications');
    Route::get('notification/{id}/delete', 'NotificationController@notificationDelete')->name('notificationDelete');

    // user update
    Route::get('/user/update/{id}', 'UserController@updateUserForm')->name('updateUserForm');
    Route::post('user/update', 'UserController@updateUser')->name('userRegistration.update');

    // single user view
    Route::get('/user/single/{id}/view', 'UserController@singleUserView')->name('singleUserView');

    Route::group(['middleware' => 'manager'], function(){
        // user registration
        Route::get('/user/registration/{type}', 'UserController@registrationForm')->name('registrationForm');
        Route::post('/user/registration', 'UserController@store')->name('userRegistration.store');

        // user view
        Route::get('/user/all/{type}/view', 'UserController@userList')->name('adminUser.list');

        // delivery boy payment
        Route::get('/payment/admin/history', 'IncomeController@adminPaymentHistory')->name('adminPaymentHistory');
        Route::post('/payment/admin/make', 'IncomeController@makePayment')->name('makePayment');
        Route::get('/payment/admin/{type}/{id}', 'IncomeController@changeOrDeletePaymentHistory')->name('changeOrDeletePaymentHistory');

        // merchant fee and payment
        Route::get('payment/merchant/history', 'MerchantTransactionController@merchantPaymentHistory')->name('merchantPaymentHistory');
        Route::get('payment/fee/history', 'MerchantTransactionController@merchantFeeHistory')->name('merchantFeeHistory');
        Route::get('payment/change/status/{type}/{id}', 'MerchantTransactionController@changeMerchantPaymentStatus')->name('changeMerchantPaymentStatus');
        Route::get('fee/change/status/{type}/{id}', 'MerchantTransactionController@changeMerchantFeeStatus')->name('changeMerchantFeeStatus');
        Route::post('payment/make/', 'MerchantTransactionController@makeMerchantPayment')->name('makeMerchantPayment');
        //fee
        Route::post('fee/make/', 'MerchantTransactionController@getDeliveryFeeFromMerchant')->name('getDeliveryFeeFromMerchant');

        // user suspend, delete and approve confirmation
        Route::get('/user/suspend/{id}/confirmation', 'UserController@userSuspendConfirmation')->name('userSuspendConfirmation');
        Route::get('/user/delete/{id}/confirmation', 'UserController@userDeleteConfirmation')->name('userDeleteConfirmation');
        Route::get('/user/approve/{id}/confirmation', 'UserController@userApproveConfirmation')->name('userApproveConfirmation');

        // admin order modify routes
        Route::get('/order/{type}/list', 'AdminOrderController@orderList')->name('orderListForAdmin');
        Route::post('/order/update/accept', 'AdminOrderController@acceptOrder')->name('acceptOrder');

        // admin delivery
        Route::get('/delivery/{type}/list', 'AdminDeliveryController@deliveryListForAdmin')->name('deliveryListForAdmin');
        Route::get('/products/change/{id}/{status_id}/status', 'AdminDeliveryController@changeStatus')->name('changeStatus');
        Route::post('assign/delivery/boy', 'AdminDeliveryController@assignForDeliver')->name('assignForDeliver');

        // resource routes
        Route::resource('area', 'AreaController');
        Route::resource('branch', 'BranchController');
        Route::resource('delivery_system', 'DeliverySystemController');
        Route::resource('cancel_reason', 'CancelController');
    });

    // merchant routes
    Route::group(['middleware'=> 'merchant', 'prefix' => 'merchant'], function (){
        Route::resource('order_request', 'OrderRequestController');
        Route::get('order/list/{type}', 'MerchantOrderController@merchantOrderList')->name('merchantOrderList');
        Route::get('order/change/status/{id}/{status}', 'MerchantOrderController@changeStatusByMerchant')->name('changeStatusByMerchant');

        // merchant payment list
        Route::get('payment/list', 'MerchantTransactionController@merchantPaymentList')->name('merchantPaymentList');
        Route::get('delivery/fee/payment/list', 'MerchantTransactionController@merchantDeliveryFeePaymentHistory')->name('merchantDeliveryFeePaymentHistory');
        Route::get('/accept/change/{type}/{id}', 'MerchantTransactionController@acceptOrRejectMerchantPayment')->name('acceptOrRejectMerchantPayment');
        Route::get('fee/change/{type}/{id}', 'MerchantTransactionController@acceptOrRejectMerchantDeliveryFee')->name('acceptOrRejectMerchantDeliveryFee');
    });

    // delivery boy routes
    Route::group(['prefix' => "boy"], function (){
       Route::get('order/{type}/list', 'BoyOrderController@orderList')->name('boy.orderList');
       Route::get('order/pick/{type}/{order_id}', 'BoyOrderController@acceptPickOrder')->name('boy.acceptPickOrder');
       Route::get('order/add/product/{order_id}', 'BoyOrderController@addProductsToOrder')->name('boy.addProductsToOrder');
       Route::post('order/add/product', 'BoyOrderController@addProductsToOrderSubmit')->name('boy.addProductsToOrderSubmit');
       Route::get('order/details/products/{id}', 'BoyOrderController@orderDetails')->name('boy.orderDetails');
       Route::get('order/delivered/office/{id}', 'BoyOrderController@deliveredToOffice')->name('boy.deliveredToOffice'); // notifyable

        // delivery routes for boy
        Route::get('delivery/products/{type}', 'BoyDeliveryController@boyDeliveryList')->name('boyDeliveryList');
        Route::get('delivery/request/accept/{id}', 'BoyDeliveryController@acceptDeliveryRequest')->name('acceptDeliveryRequest');
        Route::get('delivery/request/reject/{id}', 'BoyDeliveryController@rejectDeliveryRequest')->name('rejectDeliveryRequest');
        Route::get('delivery/collect/product/{id}', 'BoyDeliveryController@collectProductForDelivery')->name('collectProductForDelivery');
        Route::get('delivery/complete/confirm/{id}', 'BoyDeliveryController@requestToCompleteDelivery')->name('requestToCompleteDelivery');
        Route::post('delivery/cancel/', 'BoyDeliveryController@cancelOrderByBoy')->name('cancelOrderByBoy');

        // income and payment routes
        Route::get('/income/boy/history', 'IncomeController@boyIncomeHistory')->name('boyIncomeHistory');
        Route::get('/payment/boy/history', 'IncomeController@boyPaymentHistory')->name('boyPaymentHistory');
        Route::get('/payment/accept/boy/{type}/{id}', 'IncomeController@acceptPaymentRequest')->name('acceptPaymentRequest');
    });
});

// default pages (suspend and pending page)
Route::get('/account/suspend/', 'UserController@suspend')->name('userSuspend');
Route::get('/account/pending/', 'UserController@pending')->name('userPending');

app/Area.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Area extends Model
{
    protected $guarded = [''];

    // relation with branch table
    public function branch()
    {
        return $this->belongsTo('App\Branch');
    }
}

app/Http/Controllers/AreaController.php
<?php

namespace App\Http\Controllers;

use App\Area;
use App\Branch;
use Illuminate\Http\Request;

class AreaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['branches'] = Branch::all();
        $data['areas'] = Area::all();
        return view('admin.area.area', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
           'area_name' => 'required',
           'branch_id' => 'required',
        ]);

        Area::create([
           'area_name' => $request->area_name,
           'branch_id' => $request->branch_id
        ]);
        return back()->with('success', "Area created Successfully");

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'area_name' => 'required',
            'branch_id' => 'required',
        ]);

        Area::find($id)->update([
            'area_name' => $request->area_name,
            'branch_id' => $request->branch_id
        ]);
        return back()->with('success', "Area Updated Successfully");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/area/area.blade.php
@extends('layouts.adminlayout')

@section("css")
    <link href="{{ asset('admin') }}/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">
@endsection


@section("main_content")
    <div class="row clearfix">
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        List of Area
                    </h2>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        @if(count($areas) > 0)
                            <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                <thead>
                                <tr>
                                    <th>Name of Area</th>
                                    <th>Branch Name</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($areas as $area)
                                    <tr>
                                        <td>{{ $area->area_name }}</td>
                                        <td>{{ ($area->branch_id) ? $area->branch->branch_name : "" }}</td>
                                        <td style="width: 10%; white-space: nowrap">
                                            <button type="button" class="btn bg-black" data-toggle="modal" data-target="#smallModal{{ $area->id }}">Update</button>

                                            <div class="modal fade" style="white-space: normal;" id="smallModal{{ $area->id }}" tabindex="-1" role="dialog">
                                                <div class="modal-dialog modal-dialog-center" role="document">
                                                    <div class="modal-content modal-col-green">
                                                        <div class="modal-header">
                                                            <h4 class="modal-title" id="smallModalLabel">Update Area Info</h4>
                                                        </div>
                                                        <form action="{{ route('area.update', $area->id) }}" method="post">
                                                            @csrf
                                                            @method("put")
                                                            <div class="modal-body">
                                                                <div class="mb-20">
                                                                    <label for="">Area Name</label>
                                                                    <input type="text" style="width: 100%" value="{{ $area->area_name }}" class="form-control" name="area_name" placeholder="write an area name">
                                                                </div>
                                                                <div class="mb-20">
                                                                    <label for="">Select a Branch</label>
                                                                    <select name="branch_id" style="width: 100%" class="form-control">
                                                                        @foreach($branches as $branch)
                                                                            <option value="{{ $branch->id }}" {{ ($branch->id == $area->branch_id) ? "selected" : "" }}>{{ $branch->branch_name }}</option>
                                                                        @endforeach
                                                                    </select>
                                                                </div>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="submit" class="btn btn-link waves-effect" >Update</button>
                                                                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Close</button>

                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        @else
                            <h2 class="text-center mb-30">No Data Found</h2>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card">
                <div class="header">
                    <h2>Create a New Area</h2>
                </div>
                <div class="body">
                    <form action="{{ route('area.store') }}" method="post">
                        @csrf
                        <div class="mb-20">
                            <label for="">Area Name</label>
                            <input type="text" class="form-control" name="area_name" placeholder="write an area name">
                            @if($errors->has('area_name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong style="color: red; font-style: italic">{{ $errors->first('area_name') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="mb-20">
                            <label for="">Select a Branch</label>
                            <select name="branch_id" class="form-control">
                                <option disabled selected>-- Please Select --</option>
                                @foreach($branches as $branch)
                                    <option value="{{ $branch->id }}">{{ $branch->branch_name }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('branch_id'))
                                <span class="invalid-feedback" role="alert">
                                    <strong style="color: red; font-style: italic">{{ $errors->first('branch_id') }}</strong>
                                </span>
                            @endif
                        </div>
                        <input type="submit" class="btn btn-success" value="Create Area">
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section("javascript")

    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>

    {{-- --}}
    <script src="{{ asset('admin') }}/js/pages/tables/jquery-datatable.js"></script>


@endsection