routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');

Auth::routes();
Route::get('/register', 'RegistrationController@userRegistrationForm')->name('userRegistrationForm');
Route::get('/register/delivery-boy', 'RegistrationController@userRegistrationForm')->name('deliveryBoyRegistrationForm');
Route::post('/register', 'RegistrationController@userRegistrationSubmit')->name('userRegistrationSubmit');

// ajax routes
Route::get('/get/district', 'UserController@getDistrict');
Route::get('/get/upazila', 'UserController@getUpazila');
Route::get('/get/tracking_id', 'UserController@product_tracking');


// admin routes
Route::get('/home', 'HomeController@index')->name('home')->middleware('suspend');
Route::get('/personal/profile', 'HomeController@personalProfile')->name('personalProfile')->middleware('suspend');
Route::get('/update/profile', 'HomeController@updateProfile')->name('updateProfile')->middleware('suspend');

Route::group(['prefix' => 'admin', 'middleware' => ['suspend']], function(){
    // Notifications
    Route::get('notifications', 'NotificationController@index')->name('notifications');
    Route::get('notification/{id}/delete', 'NotificationController@notificationDelete')->name('notificationDelete');

    // user update
    Route::get('/user/update/{id}', 'UserController@updateUserForm')->name('updateUserForm');
    Route::post('user/update', 'UserController@updateUser')->name('userRegistration.update');

    // single user view
    Route::get('/user/single/{id}/view', 'UserController@singleUserView')->name('singleUserView');

    Route::group(['middleware' => 'manager'], function(){
        // user registration
        Route::get('/user/registration/{type}', 'UserController@registrationForm')->name('registrationForm');
        Route::post('/user/registration', 'UserController@store')->name('userRegistration.store');

        // user view
        Route::get('/user/all/{type}/view', 'UserController@userList')->name('adminUser.list');

        // delivery boy payment
        Route::get('/payment/admin/history', 'IncomeController@adminPaymentHistory')->name('adminPaymentHistory');
        Route::post('/payment/admin/make', 'IncomeController@makePayment')->name('makePayment');
        Route::get('/payment/admin/{type}/{id}', 'IncomeController@changeOrDeletePaymentHistory')->name('changeOrDeletePaymentHistory');

        // merchant fee and payment
        Route::get('payment/merchant/history', 'MerchantTransactionController@merchantPaymentHistory')->name('merchantPaymentHistory');
        Route::get('payment/fee/history', 'MerchantTransactionController@merchantFeeHistory')->name('merchantFeeHistory');
        Route::get('payment/change/status/{type}/{id}', 'MerchantTransactionController@changeMerchantPaymentStatus')->name('changeMerchantPaymentStatus');
        Route::get('fee/change/status/{type}/{id}', 'MerchantTransactionController@changeMerchantFeeStatus')->name('changeMerchantFeeStatus');
        Route::post('payment/make/', 'MerchantTransactionController@makeMerchantPayment')->name('makeMerchantPayment');
        //fee
        Route::post('fee/make/', 'MerchantTransactionController@getDeliveryFeeFromMerchant')->name('getDeliveryFeeFromMerchant');

        // user suspend, delete and approve confirmation
        Route::get('/user/suspend/{id}/confirmation', 'UserController@userSuspendConfirmation')->name('userSuspendConfirmation');
        Route::get('/user/delete/{id}/confirmation', 'UserController@userDeleteConfirmation')->name('userDeleteConfirmation');
        Route::get('/user/approve/{id}/confirmation', 'UserController@userApproveConfirmation')->name('userApproveConfirmation');

        // admin order modify routes
        Route::get('/order/{type}/list', 'AdminOrderController@orderList')->name('orderListForAdmin');
        Route::post('/order/update/accept', 'AdminOrderController@acceptOrder')->name('acceptOrder');

        // admin delivery
        Route::get('/delivery/{type}/list', 'AdminDeliveryController@deliveryListForAdmin')->name('deliveryListForAdmin');
        Route::get('/products/change/{id}/{status_id}/status', 'AdminDeliveryController@changeStatus')->name('changeStatus');
        Route::post('assign/delivery/boy', 'AdminDeliveryController@assignForDeliver')->name('assignForDeliver');

        // resource routes
        Route::resource('area', 'AreaController');
        Route::resource('branch', 'BranchController');
        Route::resource('delivery_system', 'DeliverySystemController');
        Route::resource('cancel_reason', 'CancelController');
    });

    // merchant routes
    Route::group(['middleware'=> 'merchant', 'prefix' => 'merchant'], function (){
        Route::resource('order_request', 'OrderRequestController');
        Route::get('order/list/{type}', 'MerchantOrderController@merchantOrderList')->name('merchantOrderList');
        Route::get('order/change/status/{id}/{status}', 'MerchantOrderController@changeStatusByMerchant')->name('changeStatusByMerchant');

        // merchant payment list
        Route::get('payment/list', 'MerchantTransactionController@merchantPaymentList')->name('merchantPaymentList');
        Route::get('delivery/fee/payment/list', 'MerchantTransactionController@merchantDeliveryFeePaymentHistory')->name('merchantDeliveryFeePaymentHistory');
        Route::get('/accept/change/{type}/{id}', 'MerchantTransactionController@acceptOrRejectMerchantPayment')->name('acceptOrRejectMerchantPayment');
        Route::get('fee/change/{type}/{id}', 'MerchantTransactionController@acceptOrRejectMerchantDeliveryFee')->name('acceptOrRejectMerchantDeliveryFee');
    });

    // delivery boy routes
    Route::group(['prefix' => "boy"], function (){
       Route::get('order/{type}/list', 'BoyOrderController@orderList')->name('boy.orderList');
       Route::get('order/pick/{type}/{order_id}', 'BoyOrderController@acceptPickOrder')->name('boy.acceptPickOrder');
       Route::get('order/add/product/{order_id}', 'BoyOrderController@addProductsToOrder')->name('boy.addProductsToOrder');
       Route::post('order/add/product', 'BoyOrderController@addProductsToOrderSubmit')->name('boy.addProductsToOrderSubmit');
       Route::get('order/details/products/{id}', 'BoyOrderController@orderDetails')->name('boy.orderDetails');
       Route::get('order/delivered/office/{id}', 'BoyOrderController@deliveredToOffice')->name('boy.deliveredToOffice'); // notifyable

        // delivery routes for boy
        Route::get('delivery/products/{type}', 'BoyDeliveryController@boyDeliveryList')->name('boyDeliveryList');
        Route::get('delivery/request/accept/{id}', 'BoyDeliveryController@acceptDeliveryRequest')->name('acceptDeliveryRequest');
        Route::get('delivery/request/reject/{id}', 'BoyDeliveryController@rejectDeliveryRequest')->name('rejectDeliveryRequest');
        Route::get('delivery/collect/product/{id}', 'BoyDeliveryController@collectProductForDelivery')->name('collectProductForDelivery');
        Route::get('delivery/complete/confirm/{id}', 'BoyDeliveryController@requestToCompleteDelivery')->name('requestToCompleteDelivery');
        Route::post('delivery/cancel/', 'BoyDeliveryController@cancelOrderByBoy')->name('cancelOrderByBoy');

        // income and payment routes
        Route::get('/income/boy/history', 'IncomeController@boyIncomeHistory')->name('boyIncomeHistory');
        Route::get('/payment/boy/history', 'IncomeController@boyPaymentHistory')->name('boyPaymentHistory');
        Route::get('/payment/accept/boy/{type}/{id}', 'IncomeController@acceptPaymentRequest')->name('acceptPaymentRequest');
    });
});

// default pages (suspend and pending page)
Route::get('/account/suspend/', 'UserController@suspend')->name('userSuspend');
Route::get('/account/pending/', 'UserController@pending')->name('userPending');

app/Http/Controllers/OrderRequestController.php
<?php

namespace App\Http\Controllers;

use App\Notice;
use App\Order;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class OrderRequestController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [];
        if (Auth::user()->role_id == 1){
            $data['merchants'] = User::where('role_id', 3)->get();
        }elseif (Auth::user()->role_id == 2){
            $data['merchants'] = User::where(['role_id' => 3, 'branch_id' => Auth::user()->branch_id])->get();
        }
        return view('admin.order_request.request_form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
           'product_quantity' => 'required|gt:0',
           'weight' => 'required|gt:0'
        ]);
        $order = new Order();
        $order->user_id = $request->merchant_id;
        $order->branch_id = auth::user()->branch_id;
        $order->product_quantity = $request->product_quantity;
        $order->weight = $request->weight;
        $order->tracking_id = '';
        $order->created_at = Carbon::now();
        $order->save();
        $order->tracking_id = "ECR" . date("ymd") . $order->id;
        $order->save();

        // notification
        Notice::create([
           'type' => 'Order Request',
           'details' => auth::user()->name . ' has created an order request',
           'branch_id' => auth::user()->branch_id,
        ]);
        return back()->with('success', "Order request submitted successfully");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if ($id == 'pending'){
            $data['orders'] = Order::where([
                ['user_id', auth::id()],
                ['main_order_status_id', 1]
            ])->get();
        }elseif($id == 'processing'){
            $data['orders'] = Order::where([
                ['user_id', auth::id()],
                ['main_order_status_id', 2]
            ])->orwhere([
                ['user_id', auth::id()],
                ['main_order_status_id', 3]
            ])->orwhere([
                ['user_id', auth::id()],
                ['main_order_status_id', 4]
            ])->get();
        }elseif ($id = 'completed'){
            $data['orders'] = Order::where([
                ['user_id', auth::id()],
                ['main_order_status_id', 5]
            ])->get();
        }
        $data['type'] = $id;
        return view('admin.order_request.index', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'product_quantity' => 'required|gt:0',
            'weight' => 'required|gt:0'
        ]);
        if ($order->user_id != auth::id()){
            return back()->with('error', "Sorry! You haven't permission to delete this order");
        }
        $order = Order::find($id);
        $order->product_quantity = $request->product_quantity;
        $order->weight = $request->weight;
        $order->updated_at = Carbon::now();
        $order->save();

        return back()->with('success', "Order request updated successfully");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $order = Order::find($id);
        if ($order->user_id != auth::id()){
            return back()->with('error', "Sorry! You haven't permission to delete this order");
        }
        $order->delete();
        return back()->with('success', "Order Request Deleted Successfully");
    }
}

resources/views/admin/order_request/index.blade.php
@extends('layouts.adminlayout')

@section("css")
    <link href="{{ asset('admin') }}/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">
@endsection


@section("main_content")
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h2>
                        List of {{ ucfirst($type) }} Orders
                    </h2>
                </div>
                <style>
                    ._1{
                        padding: 5px 10px; background-color: #1b4b72; color: #fff
                    }
                    ._2{
                        padding: 5px 10px; background-color: #9f105c; color: #fff
                    }
                    ._3{
                        padding: 5px 10px; background-color: #4a148c; color: #fff
                    }
                    ._4{
                        padding: 5px 10px; background-color: #0d47a1; color: #fff
                    }
                    ._5{
                        padding: 5px 10px; background-color: green; color: #fff;
                    }
                </style>
                <div class="body">
                    <div class="table-responsive">
                        @if(count($orders) > 0)
                            <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                <thead>
                                <tr>
                                    <th>Order ID</th>
                                    <th>Product Quantity</th>
                                    <th>Weight</th>
                                    <th>Order Status</th>
                                    <th>Created At</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                    @foreach($orders as $order)
                                        <?php
                                            switch ($order->main_order_status_id){
                                                case 1: $class = "_1";
                                                break;
                                                case 2: $class = "_2";
                                                break;
                                                case 3: $class = "_3";
                                                break;
                                                case 4: $class = "_4";
                                                break;
                                                case 5: $class = "_5";
                                                break;
                                            }
                                        ?>
                                    <tr>
                                        <td>{{ $order->tracking_id }}</td>
                                        <td class="text-center">{{ $order->product_quantity }}</td>
                                        <td class="text-center">{{ $order->weight }}</td>
                                        <td class="text-center"><span class="{{ $class }}">{{ $order->main_order_status->status_title }}</span></td>
                                        <td class="text-center">{{ $order->created_at->diffForHumans() }}</td>
                                        <td style="width: 10%; white-space: nowrap">
                                            @if($order->main_order_status_id != 1)
                                                <a href="{{ route('boy.orderDetails', $order->id) }}" class="btn bg-black">Details</a>
                                            @endif

                                            @if($order->main_order_status_id == 1)
                                                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#update{{ $order->id }}">Update</button>

                                                <div style="white-space: normal" class="modal fade" id="update{{ $order->id }}" tabindex="-1" role="dialog">
                                                    <div class="modal-dialog modal-dialog-center modal-sm" role="document">
                                                        <div class="modal-content modal-col-green">
                                                            <div class="modal-header">
                                                                <h4 class="modal-title" id="smallModalLabel">Update Order Request</h4>
                                                            </div>
                                                            <form action="{{ route('order_request.update', $order->id) }}" method="post">
                                                                @csrf
                                                                @method('put')
                                                                <div class="modal-body">
                                                                    <div class="mb-20">
                                                                        <label for="">Product Quantity</label>
                                                                        <input type="text" value="{{ $order->product_quantity }}" name="product_quantity" style="width: 100%; color: #000" class="form-control">
                                                                    </div>
                                                                    <div class="mb-20">
                                                                        <label for="">Approximate Weight</label>
                                                                        <input type="text" value="{{ $order->weight }}" name="weight" style="width: 100%; color: #000" class="form-control">
                                                                    </div>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="submit" class="btn btn-link" style="background-color: rgba(0,0,0,.1)">Update</button>
                                                                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">No</button>
                                                                </div>
                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>
                                                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#approve{{ $order->id }}">Delete</button>

                                                <div class="modal fade" id="approve{{ $order->id }}" tabindex="-1" role="dialog">
                                                    <div class="modal-dialog modal-dialog-center modal-sm" role="document">
                                                        <div class="modal-content modal-col-red">
                                                            <div class="modal-header">
                                                                <h4 class="modal-title" id="smallModalLabel">Confirmation!</h4>
                                                            </div>
                                                            <div class="modal-body text-center">
                                                                <h4>Are you sure to Delete?</h4>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <a href="" class="btn btn-link" style="background-color: rgba(0,0,0,.1)" onclick="event.preventDefault(); document.getElementById('delete-form').submit();">
                                                                    Yes
                                                                </a>

                                                                <form id="delete-form" action="{{ route('order_request.destroy', $order->id) }}" method="POST" style="display: none;">
                                                                    @method("delete")
                                                                    @csrf
                                                                </form>
                                                                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">No</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            @endif
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @else
                            <h2 class="text-center mb-30">No Data Found</h2>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section("javascript")

    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>

    {{-- --}}
    <script src="{{ asset('admin') }}/js/pages/tables/jquery-datatable.js"></script>

@endsection

resources/views/admin/order_request/request_form.blade.php
@extends('layouts.adminlayout')

@section("main_content")
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Create a new order Request</h2>
                </div>
                <div class="body">
                    <form action="{{ route('order_request.store') }}" method="post">
                        @csrf
                        @merchant
                        <input type="hidden" name="merchant_id" value="{{ auth::id() }}">
                        @endmerchant
                        <div class="row">
                            <div class="col-md-6 col-md-offset-3">
                                @manager
                                <div class="mb-20">
                                    <label for="">Select a Merchant</label>
                                    <select name="merchant_id" class="form-control">
                                        <option disabled selected>-- Select a Merchant --</option>
                                        @foreach($merchants as $merchant)
                                            <option value="{{ $merchant->id }}">{{ $merchant->name }} ({{ $merchant->phone }})</option>
                                        @endforeach
                                    </select>
                                </div>
                                @endmanager
                                <div class="mb-20">
                                    <label for="">Product Quantity</label>
                                    <input type="number" name="product_quantity" class="form-control" placeholder="How many Product have to deliver">
                                    @if ($errors->has('product_quantity'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong style="color: red; font-style: italic">{{ $errors->first('product_quantity') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="mb-20">
                                    <label for="">Approximate Weight</label>
                                    <input type="number" name="weight" class="form-control" placeholder="Approximate weight of products">
                                    @if ($errors->has('weight'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong style="color: red; font-style: italic">{{ $errors->first('weight') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="text-center">
                                    <input type="submit" class="btn btn-success" value="Create Request">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection